parameters:
#    mods_generator.example.class: DSNEmpresas\ModsGenerator\ModsGeneratorBundle\Example

services:
#    mods_generator.example:
#        class: %mods_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
